import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import './../../assets/css/Style.scss';
import { NextIntlClientProvider } from "next-intl";
import { SearchProvider } from "../providers/SearchProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
    params: { locale }
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string }
}>) {



    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <NextIntlClientProvider locale={locale}>
                    <SearchProvider>
                        {children}
                    </SearchProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
