import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { NextIntlClientProvider } from "next-intl";
import { SearchProvider } from "../providers/SearchProvider";
import './../../assets/css/Style.scss';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};





// --- 1. Define the actual locales supported ---
/*export function generateStaticParams() {
    // Use the exact list of locales defined in your 'i18n/routing' file
    return [{ locale: 'en' }, { locale: 'fr' }];
}*/

export function generateStaticParams() {
    // Return the specific locales your application supports
    // This tells Next.js how to handle the `[locale]` segment for static paths
    return [
        { locale: 'en' },
        { locale: 'fr' } // Add any other locales you support
    ];
}

export default async function RootLayout({ children, params }: { children: React.ReactNode, params: Promise<{ locale: string }> }) {
    const { locale } = await params;

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <NextIntlClientProvider locale={locale}>
                    <SearchProvider>
                        {children}
                    </SearchProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
